version: "3.8"

services:
  qdrant-search-service:
    build: .
    container_name: qdrant-search-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ALLOW_ALL_CORS=true
    env_file:
      - .env
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
    networks:
      - qdrant-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Connects to existing QDrant instance on host

networks:
  qdrant-network:
    driver: bridge
